name: SCP Files ci-cd 
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
 build-and-push:
    runs-on: ubuntu-latest
    name: Zip,Copy to S3 and Update Lambda

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 13.38.4.127
          username: ec2-user
          passphrase: ${{ secrets.key }}
          port: 22
          source: "deploy.tar"
          target: "destination/folder"
          
 
